# Generated by Django 6.0.3 on 2026-03-20 19:12

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Loja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('endereco', models.CharField(max_length=200)),
                ('numero', models.CharField(max_length=10)),
                ('bairro', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=2)),
                ('cep', models.CharField(max_length=9)),
                ('prazo_retirada_dias', models.IntegerField(default=1)),
                ('ativa', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDENTE', 'Aguardando Retirada'), ('CONCLUIDO', 'Retirado'), ('CANCELADO', 'Cancelado')], default='PENDENTE', max_length=15)),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmacia.loja')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30, unique=True)),
                ('codigo', models.CharField(max_length=30, unique=True)),
                ('descricao', models.CharField(default='', max_length=200, unique=True)),
                ('categoria', models.CharField(max_length=50)),
                ('preco_custo', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('unidade_medida', models.CharField(max_length=20)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('codigo', ''), _negated=True), name='codigo_nao_vazio'), models.CheckConstraint(condition=models.Q(('descricao', ''), _negated=True), name='descricao_nao_vazia'), models.CheckConstraint(condition=models.Q(('categoria', ''), _negated=True), name='categoria_nao_vazia'), models.CheckConstraint(condition=models.Q(('unidade_medida', ''), _negated=True), name='unidade_medida_nao_vazia')],
            },
        ),
        migrations.CreateModel(
            name='ItemPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField()),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='farmacia.pedido')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmacia.produto')),
            ],
        ),
        migrations.CreateModel(
            name='Estoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField()),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmacia.loja')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmacia.produto')),
            ],
            options={
                'unique_together': {('produto', 'loja')},
            },
        ),
    ]
