# Generated by Django 6.0.3 on 2026-03-29 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmacia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estoque',
            name='data_ultima_atualizacao',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
