# Generated by Django 6.0.3 on 2026-04-20 18:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmacia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='dataValidade',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data de validade'),
            preserve_default=False,
        ),
    ]
