# Generated by Django 6.0.3 on 2026-04-20 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmacia', '0002_estoque_data_ultima_atualizacao'),
        ('farmacia', '0002_produto_datavalidade'),
    ]

    operations = [
    ]
